### ISSUE TITLE
Wiki link incorrect

### ISSUE THREAD

**Issue by nicolasguzca** [ralivue/notific8#47]
Hello! The wiki link on the readme (https://github.com/ralivue/notific8/blob/master/wiki) leads to a page not found. (I guess it should be https://github.com/ralivue/notific8/wiki)

Great plugin by the way!

**Comment by willsteinmetz** [comment]
Got it updated with 2.3.1 release. Thanks for catching that!

**Comment by willsteinmetz** [comment]
Apparently it's something with the way GitHub is rendering it.
